import BaseFractal from "../../../Model/Guildwars/BaseFractal";

const GW_FRACTALS: Array<BaseFractal> = [
    // T1
    { level: 1, name: "Volcanic" },
    { level: 2, name: "Uncategorized" },
    { level: 3, name: "Snowblind" },
    { level: 4, name: "Urban Battleground" },
    { level: 5, name: "Swampland" },
    { level: 6, name: "Cliffside" },
    { level: 7, name: "Aquatic Ruins" },
    { level: 8, name: "Underground Facility" },
    { level: 9, name: "Molten Furnace" },
    { level: 10, name: "Molten Boss" },
    { level: 11, name: "Deepstone" },
    { level: 12, name: "Siren's Reef" },
    { level: 13, name: "Chaos" },
    { level: 14, name: "Aetherblade" },
    { level: 15, name: "Thaumanova Reactor" },
    { level: 16, name: "Twilight Oasis" },
    { level: 17, name: "Swampland" },
    { level: 18, name: "Captain Mai Trin Boss" },
    { level: 19, name: "Volcanic" },
    { level: 20, name: "Solid Ocean" },
    { level: 21, name: "Cliffside" },
    { level: 22, name: "Molten Furnace" },
    { level: 23, name: "Nightmare" },
    { level: 24, name: "Shattered Observatory" },
    { level: 25, name: "Sunqua Peak" },

    // T2
    { level: 26, name: "Aquatic Ruins" },
    { level: 27, name: "Snowblind" },
    { level: 28, name: "Volcanic" },
    { level: 29, name: "Underground Facility" },
    { level: 30, name: "Chaos" },
    { level: 31, name: "Urban Battleground" },
    { level: 32, name: "Swampland" },
    { level: 33, name: "Deepstone" },
    { level: 34, name: "Thaumanova Reactor" },
    { level: 35, name: "Solid Ocean" },
    { level: 36, name: "Uncategorized" },
    { level: 37, name: "Siren's Reef" },
    { level: 38, name: "Chaos" },
    { level: 39, name: "Molten Furnace" },
    { level: 40, name: "Molten Boss" },
    { level: 41, name: "Twilight Oasis" },
    { level: 42, name: "Captain Mai Trin Boss" },
    { level: 43, name: "Thaumanova Reactor" },
    { level: 44, name: "Uncategorized" },
    { level: 45, name: "Solid Ocean" },
    { level: 46, name: "Aetherblade" },
    { level: 47, name: "Cliffside" },
    { level: 48, name: "Nightmare" },
    { level: 49, name: "Shattered Observatory" },
    { level: 50, name: "Sunqua Peak" },

    // T3
    { level: 51, name: "Snowblind" },
    { level: 52, name: "Volcanic" },
    { level: 53, name: "Underground Facility" },
    { level: 54, name: "Siren's Reef" },
    { level: 55, name: "Thaumanova Reactor" },
    { level: 56, name: "Swampland" },
    { level: 57, name: "Urban Battleground" },
    { level: 58, name: "Molten Furnace" },
    { level: 59, name: "Twilight Oasis" },
    { level: 60, name: "Solid Ocean" },
    { level: 61, name: "Aquatic Ruins" },
    { level: 62, name: "Uncategorized" },
    { level: 63, name: "Chaos" },
    { level: 64, name: "Thaumanova Reactor" },
    { level: 65, name: "Aetherblade" },
    { level: 66, name: "Urban Battleground" },
    { level: 67, name: "Deepstone" },
    { level: 68, name: "Snowblind" },
    { level: 69, name: "Cliffside" },
    { level: 70, name: "Molten Boss" },
    { level: 71, name: "Aetherblade" },
    { level: 72, name: "Captain Mai Trin Boss" },
    { level: 73, name: "Nightmare" },
    { level: 74, name: "Shattered Observatory" },
    { level: 75, name: "Sunqua Peak" },

    // T4
    { level: 76, name: "Aquatic Ruins" },
    { level: 77, name: "Swampland" },
    { level: 78, name: "Siren's Reef" },
    { level: 79, name: "Uncategorized" },
    { level: 80, name: "Solid Ocean" },
    { level: 81, name: "Underground Facility" },
    { level: 82, name: "Thaumanova Reactor" },
    { level: 83, name: "Molten Furnace" },
    { level: 84, name: "Deepstone" },
    { level: 85, name: "Urban Battleground" },
    { level: 86, name: "Snowblind" },
    { level: 87, name: "Twilight Oasis" },
    { level: 88, name: "Chaos" },
    { level: 89, name: "Swampland" },
    { level: 90, name: "Molten Boss" },
    { level: 91, name: "Uncategorized" },
    { level: 92, name: "Volcanic" },
    { level: 93, name: "Snowblind" },
    { level: 94, name: "Cliffside" },
    { level: 95, name: "Captain Mai Trin Boss" },
    { level: 96, name: "Aetherblade" },
    { level: 97, name: "Chaos" },
    { level: 98, name: "Nightmare" },
    { level: 99, name: "Shattered Observatory" },
    { level: 100, name: "Sunqua Peak" }
];

export default GW_FRACTALS;
