const GW_FRACTALS: Record<number, string> = {
    //T1
    1: "Volcanic",
    2: "Uncategorized",
    3: "Snowblind",
    4: "Urban Battleground",
    5: "Swampland",
    6: "Cliffside",
    7: "Aquatic Ruins",
    8: "Underground Facility",
    9: "Molten Furnace",
    10: "Molten Boss",
    11: "Deepstone",
    12: "Siren's Reef",
    13: "Chaos",
    14: "Aetherblade",
    15: "Thaumanova Reactor",
    16: "Twilight Oasis",
    17: "Swampland",
    18: "Captain Mai Trin Boss",
    19: "Volcanic",
    20: "Solid Ocean",
    21: "Cliffside",
    22: "Molten Furnace",
    23: "Nightmare",
    24: "Shattered Observatory",
    25: "Sunqua Peak",

    //T2
    26: "Aquatic Ruins",
    27: "Snowblind",
    28: "Volcanic",
    29: "Underground Facility",
    30: "Chaos",
    31: "Urban Battleground",
    32: "Swampland",
    33: "Deepstone",
    34: "Thaumanova Reactor",
    35: "Solid Ocean",
    36: "Uncategorized",
    37: "Siren's Reef",
    38: "Chaos",
    39: "Molten Furnace",
    40: "Molten Boss",
    41: "Twilight Oasis",
    42: "Captain Mai Trin Boss",
    43: "Thaumanova Reactor",
    44: "Uncategorized",
    45: "Solid Ocean",
    46: "Aetherblade",
    47: "Cliffside",
    48: "Nightmare",
    49: "Shattered Observatory",
    50: "Sunqua Peak",

    //T3
    51: "Snowblind",
    52: "Volcanic",
    53: "Underground Facility",
    54: "Siren's Reef",
    55: "Thaumanova Reactor",
    56: "Swampland",
    57: "Urban Battleground",
    58: "Molten Furnace",
    59: "Twilight Oasis",
    60: "Solid Ocean",
    61: "Aquatic Ruins",
    62: "Uncategorized",
    63: "Chaos",
    64: "Thaumanova Reactor",
    65: "Aetherblade",
    66: "Urban Battleground",
    67: "Deepstone",
    68: "Snowblind",
    69: "Cliffside",
    70: "Molten Boss",
    71: "Aetherblade",
    72: "Captain Mai Trin Boss",
    73: "Nightmare",
    74: "Shattered Observatory",
    75: "Sunqua Peak",

    //T4
    76: "Aquatic Ruins",
    77: "Swampland",
    78: "Siren's Reef",
    79: "Uncategorized",
    80: "Solid Ocean",
    81: "Underground Facility",
    82: "Thaumanova Reactor",
    83: "Molten Furnace",
    84: "Deepstone",
    85: "Urban Battleground",
    86: "Snowblind",
    87: "Twilight Oasis",
    88: "Chaos",
    89: "Swampland",
    90: "Molten Boss",
    91: "Uncategorized",
    92: "Volcanic",
    93: "Snowblind",
    94: "Cliffside",
    95: "Captain Mai Trin Boss",
    96: "Aetherblade",
    97: "Chaos",
    98: "Nightmare",
    99: "Shattered Observatory",
    100: "Sunqua Peak"

}

export default GW_FRACTALS;
